`Comprator`s expose, verify-examples, test v2
owanturist/elm-avl-tree pull request #7
Opened 2022-11-04 16:03 UTC by lue-bird

add
- `AVL.Set.keyComparator`, `AVL.Dict.keyComparator`
- `elm-verify-examples` for existing example code
- test v2 adaptations

2022-11-09 10:12 UTC, owanturist requested changes
Hi @lue-bird!

Thank you very much for your effort to improve the library. I really appreciate it. Hope you found that Dict/Set implementation useful for your personal or professional needs.

I see at least three major vectors of the changes, that can be easily done separately for the sake of easier PR processing:
1. the `keyComparator` function
2. docs/readme update
3. testing library upgrade + enhancement of `DictTests` with `dictFuzz` and `expectEqualDicts`

And I'd be happy to approve some of them, but not altogether. Especially in cases that accidentally change source code/docs style.

Nevertheless, I'd love to approve the PR and merge those three vectors in one run when all comments are resolved.

Here I'd like to address the suggestions mentioned in the PR description:
> rename AVL.X → X.Avl. It's the convention in elm and easier to read

It seems like I am far away from the modern elm conventions. Maybe you can link me an article describing that particular one? But in any case I'd not really like to rename the modules because it will cause major version for almost no reason, which I want to avoid. Historically it was an idea to implement AVL tree algorithm with Elm, and then to use it for Dict and Set. However I don't really get the point of easier readability `AVL.Dict` vs `Dict.AVL` to be honest.

> add `Dict.keysSet : Dict key value -> Set key`

It might be a good idea since Set will use the same comparator as Dict.

> link packages that help creating Comparators. A list like (might be incomplete)

I don't really get it tbh. I assume that if a developer needs a Dict/Set with custom comparator (s)he aware of the comparator idea at this point. But if not maybe they should use Dict/Set from the elm/core.


I am sorry for the long delay in my feedback - was pretty busy the whole week.

2022-11-09 10:12 UTC, owanturist commented on .gitignore
> +VerifyExamples/
I am not sure what that folder does and why it is ignored. May I ask you to bring some light here?

2022-11-09 10:12 UTC, owanturist commented on README.md
> +        , ( ID 2, { id = ID 2, name = "Chuck", age = 33, height = 1.75 } )
that's more clear indeed 💯

2022-11-09 10:12 UTC, owanturist commented on elm.json
> +}
I can't recall if the elm CLI removes that EOF but can I ask you to bring it back?

<img width="164" alt="Screenshot 2022-11-05 at 6 43 52 PM" src="https://user-images.githubusercontent.com/8354670/200133836-55253ba4-9c48-4ea3-9b9c-5c6110526c1b.png">

2022-11-09 10:12 UTC, owanturist commented on src/AVL/Dict.elm
> +    Dict.get "Spike" animals --> Nothing
I don't see why `==` is replaced with `-->`. 

`Dict.get "Tom" animals == Just Cat` is literally True in Elm.

This is actually a copy-cat from `elm/core` package [`Dict.get`](https://package.elm-lang.org/packages/elm/core/latest/Dict#get):

<img width="654" alt="Screenshot 2022-11-09 at 9 58 48 AM" src="https://user-images.githubusercontent.com/8354670/200785848-1c62befc-d0c2-4738-85d0-5589324e72ab.png">

I wonder if `-->` is considered to be more readable, so maybe you might make a PR to the `elm/core` repo?

2022-11-09 10:12 UTC, owanturist commented on src/AVL/Dict.elm
> +    dict |> Internal.dictKeyComparator
I am not sure I see many reasons to use `|>` operator here because the expression is too primitive

```elm
dict |> Internal.dictKeyComparator

-- vs

Internal.dictKeyComparator dict
```

The `|>` operator is used in very few places across the source code, I'd like to stick to the same code style as much as possible.

2022-11-09 10:12 UTC, owanturist commented on src/AVL/Set.elm
> -    ids : Set ID User
great catch!

2022-11-09 10:12 UTC, owanturist commented on src/AVL/Dict.elm
> +    --> LT
Maybe I was too long away from the elm code, but it takes quite some time to understand the sense of that expression. IMO `(Dict.keyComparator dict) "A" "Z"` is way easier to read.

2022-11-09 10:12 UTC, owanturist commented on tests/elm-verify-examples.json
> +{
I am not sure I know what that json file does. Is it something new added to elm test library?

2022-11-09 10:12 UTC, owanturist commented on tests/DictTests.elm
> -import Test exposing (Test, describe, fuzz, fuzz2, test)
I don't think I can agree with changing the exposed functions list, because it causes the major part of changes for that test suite. Can I ask you to revert it back so the changes are more about the actual package update?

2022-11-09 10:12 UTC, owanturist commented on tests/DictTests.elm
> +                (expected |> Dict.toList)
It is really an extra cognitive load, what is wrong with `(Dict.toList expected)`?

2022-11-09 10:12 UTC, owanturist commented on tests/DictTests.elm
> +    { key : Fuzzer comparableKey, value : Fuzzer value }
Do you think making the `dictFuzz` a two-arguments function makes sense? It looks pretty natural to pass the key fuzzer first and value fuzzer next.

2022-11-09 10:12 UTC, owanturist commented on tests/DictTests.elm
> +        Fuzz.list (Fuzz.pair nodeFuzz.key nodeFuzz.value)
Here I see a perfect use case of `|>` in opposition to the rest I commented

```elm
Fuzz.pair nodeFuzz.key nodeFuzz.value
  |> Fuzz.list
  |> Fuzz.map Dict.fromList
```

2022-11-09 10:12 UTC, owanturist commented on tests/DictTests.elm
> +import Expect exposing (Expectation)
The test file has a bunch of changes but I don't see any related to the actual lib update. May I ask you to add a couple of test cases against the new `keyComparator` function?

2022-11-09 12:12 UTC, lue-bird commented on .gitignore
> +VerifyExamples/
elm-verify-examples automatically generates tests from documentation examples in that directory. It's not something to put in git bc it should be buit locally

2022-11-09 12:13 UTC, lue-bird commented on src/AVL/Dict.elm
> +    Dict.get "Spike" animals --> Nothing
Again, that's how elm-verify-examples knows how to auto-generate tests from the examples

2022-11-09 12:15 UTC, lue-bird commented on tests/elm-verify-examples.json
> +{
It's what tells elm-verify-examples which files to auto-generate tests from doc examples for

2022-11-09 12:17 UTC, lue-bird commented on tests/DictTests.elm
> +import Expect exposing (Expectation)
What tests would you want to see there? It will always be the same function you put in

2022-11-09 12:33 UTC, lue-bird commented on elm.json
> +}
readded. Yes, elm-format removes it automatically

2022-11-09 12:35 UTC, lue-bird commented on tests/DictTests.elm
> -import Test exposing (Test, describe, fuzz, fuzz2, test)
reverted `Test.fuzz` functions to unqualified

2022-11-09 12:43 UTC, lue-bird commented
Ok I think everything else you commented is up to everyone's personal preference.

  - Replacing a single `subject |> withSubject` with `withSubject subject` is inconsistent to the order of other pipelines but I guess everyone reads code differently :)
  - Replacing `dictFuzz { key, value }` with  `dictFuzz key value` is less descriptive and you lose track of context more easily on construction but is also simpler

2022-11-09 20:03 UTC, owanturist commented on tests/DictTests.elm
> +import Expect exposing (Expectation)
>  It will always be the same function you put in

Indeed, that's what can be tested for sure

2022-11-09 20:21 UTC, owanturist reviewed
Hey @lue-bird,

Thanks for the quick update!

I see that most of the changes in the test file are caused by elm formatter but not by changing of the exposed functions. If I'd known it I didn't ask you to change it back, my apologies.

I must be really out of elm track but I honestly don't get your point here

> Replacing a single `subject |> withSubject `with `withSubject subject` is inconsistent to the order of other pipelines

but I completely agree with 

> I guess everyone reads code differently :)

and that's why I believe it is important to follow the same codestyle of whatever sourcecode environment you are in.

May I ask you to clarify what you mean under `so change it back if you want` please?

2022-11-09 20:21 UTC, owanturist commented on tests/DictTests.elm
> +          <|
oh lord, the changes were actually caused by different elm format versions you and I (3 years ago) are/were using

2022-11-09 20:21 UTC, owanturist commented on src/AVL/Dict.elm
> +    Dict.get "Spike" animals --> Nothing
I get it, that's pretty cool thing!

2022-11-09 21:28 UTC, lue-bird commented
> May I ask you to clarify what you mean under so change it back if you want please?

Repo owners can push manual edits to the PR as well

2022-11-20 14:38 UTC, owanturist commented
I've got some spare time in between and finally made the final tweaks around the PR.

After all, I decided to split out the changes directly to the https://github.com/owanturist/elm-avl-dict repo:
1. https://github.com/owanturist/elm-avl-dict/pull/8 where all node/elm dependencies have been updated alongside making affected source code changes
2. https://github.com/owanturist/elm-avl-dict/pull/9 where elm-verify-examples has been appropriately configured (no need to install it globally) and integrated to test pipeline alongside transforming the examples' code 

Due to the abovementioned changes, I had to rebase the master branch of your fork and push it back. That leads to the pull request having only changes related to the extension of the package API and fewer (or none) chore changes.
I also made some corrections regarding my personal preferences.

Thank you @lue-bird once again for your effort to extend the package API and improve the developing environment!

2022-11-20 14:40 UTC, owanturist approved these changes

2022-11-20 14:47 UTC, lue-bird commented
By the way, I was able to create a version which removes the function from the structure entirely while still ensuring given compare functions are the same: [`KeySet`](https://dark.elm.dmy.fr/packages/lue-bird/elm-keysset/latest/)

2022-11-20 14:57 UTC, owanturist commented
> By the way, I was able to create a version of this which removes the function from the structure entirely while still ensuring given compare functions are the same: [KeySet](https://dark.elm.dmy.fr/packages/lue-bird/elm-keysset/latest/)

Nice job! Does it also extract a value by key during time proportional `O(logN)` where `N` is the size of a data set?

2022-11-20 14:57 UTC, lue-bird commented
yes

2022-11-20 15:04 UTC, merged